import { BackgroundImage } from '@/components'
import { Routes } from '@/utils'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import '../../styles/globals.css'
import { LinkBack } from './components'

export const metadata = {
  title: 'Chat Box - Authentication',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

async function AuthLayout({ children }: Props) {
  const session = await getServerSession()
  if (session) redirect(Routes.Chatbox)

  return (
    <main className='lg:grid lg:grid-cols-2'>
      <LinkBack />
      <BackgroundImage priority />
      {children}
    </main>
  )
}

export default AuthLayout
