import '../../styles/globals.css'

export const metadata = {
  title: 'Chat Box - App',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

function ChatboxLayout({ children }: Props) {
  return (
    <main>
      <p className='font-medium'>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reiciendis expedita sapiente, eius, obcaecati
        laboriosam officiis numquam accusamus omnis quibusdam aspernatur cumque vitae deserunt nesciunt totam nemo ea
        earum provident repellat!
      </p>
      {children}
    </main>
  )
}

export default ChatboxLayout
