import { Header } from '@/components'
import { Routes } from '@/utils'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import '../../styles/globals.css'

export const metadata = {
  title: 'Chat Box - Landing',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

async function LandingLayout({ children }: Props) {
  const session = await getServerSession()
  if (session) redirect(Routes.Chatbox)

  return (
    <>
      <Header />
      {children}
    </>
  )
}

export default LandingLayout
